terminate called after throwing an instance of 'std::bad_alloc'
  what():  St9bad_alloc
sh: line 1:   471 Aborted                 ./htn-solver2 htn_domain_novalues.pddl htn_probs/012.htn_prob

real	0m50.711s
user	0m44.847s
sys	0m5.862s
